### ISSUE TITLE
二次配布をしてもいいでしょうか

### ISSUE THREAD

**Issue by koiru-2000** [UMAGODi/HSP3-constant#1]
constant.as（constant_pX.as含む）を使用したソースコードを配布する場合に、そのconstant.asらも配布していいでしょうか？

**Comment by UMAGODi** [comment]
二次配布に関しては、配布物のreadme等に私の名前「UMAGODi」もしくはこのレポジトリのURL「github.com/UMAGODi/HSP3-constant」を記載していただければ可能です。

**Comment by koiru-2000** [comment]
なるほど。ありがとうございました。
